### ISSUE TITLE
Support new questions type

### ISSUE THREAD

**Issue by Girardvjonathan** [Girardvjonathan/GIFT-google-quiz-plugin#1]
These questions type should be supported by the plugin:

- [x] Multiple choices question
- [x] Short answer
- [ ] Matched Pair
- [x] Numerical Answer
- [x] Essay Answer

**Comment by Girardvjonathan** [comment]
For matched pair see https://developers.google.com/apps-script/reference/forms/checkbox-grid-item
Checkbox grid item.

**Comment by fuhrmanator** [comment]
Completely new version of add-on since February, so I'm closing.
