### ISSUE TITLE
Parser errors on HTML code

### ISSUE THREAD

**Issue by wmachiel** [Girardvjonathan/GIFT-google-quiz-plugin#15]
Parsing the following code into the [online parser](https://fuhrmanator.github.io/GIFT-grammar-PEG.js/docs/editor/editor.html?text=xLHDS-es55q_VeLAPrut1HkS1maFo90qv2DD89Csa9IEHxOkjh0iEP9i1phjR--r6wPjfejqdnajxhTrppcouv3d78pbIWw8rplq294qXG4vUUYqvcwdCHYyMeF1Bx5DnQ_3RBoWbkpuHX8698A2Qf04Z-Q6X-exGmA-8J5OKe9EC4wf96fDU5slKkpWCY85Ha50Oh4jZ07Jnb8XgELWZeTEDXxYuMb4Z0vNesPiRMPM0ySHiTUEb8e4v0PqgAG5QTkXIXtFFryUtWizxwkhoUPfKjp-V7MqJUrBQzQ_cyfUj5WlbfiaS-tB6LnyEVcnhv9yzzWrtUxZwVGfBXwkUcbdxitlMb6sIAwNoIHSCx-yU3xqrIwQNM-yeuVpsOquCEAd8WbEB-2MJSAEzyCqd2xNwMNt_kWy-6BaP3KgkmUksoHKMBmx8kZFE_wPWD2_KGn4UvD5JL9oPcDCrvKny2YkYhtA2mKr1XtSlwN1P4eQNW2XrYgVfpG2FyZHbhw55ziA5DffSxn7BT2r-LlZqmZTirUGGIFi5Ky5w599XXuwJ2bDOcujV4-CrLHWk6AhXCXakgvXG1W8aErgQEFJ7_yrCz1KichgQzctmupWh4ZY4Y4I1Bev_Ym3atqTyhL6XH4NC_zSkuThSuRMrcQ2Rh7XBVDbMRQtAhTv03NVa0R0dFjPRyV0dlPltMEQMrKrhqRkPvfcNuLIsMhKgUtwgu7I3FG-pGjVAChyJ0aUOfDNHrF5y47K2-5o-tOJgvBBjThtLiBJIfXzNeF0L9FORGPuwOeNftelVzFSEt0hYlvQV_mMInNcgFmAodzX-m7c_m3pVMAlLRwNBPJmLk4VQByRxSk4b02s_jbB3lQR3_pUYz_lZSQV) works, but not into the plugin.
Code is generated as a GIFT export from Moodle 3.7.
Thanks in advance for any help.

// question: 3683  name: BV1-P01
::BV1-P01::[html]<p>Wat zijn de gevaren en risico's bij het werken aan of in de omgeving van elektrische installaties?</p><p><img src\="https\://lh3.googleusercontent.com/3_GX8SlrP7oJAjZAvNUJ9ymtx-O7QFn6gWfWXjkp0txEeH5BL7okuzY2s22YCFZhvVJ6m1P3PQ-gpWkKXkAcfd_wHq8_ozgOKj39VGOMl4slTvkbCHeNdAc13DFcFXfmI2S9Gb5snA\=w2400" alt\="BV1_P1_Elec_Model.jpg" width\="400" height\="300" class\="img-responsive atto_image_button_text-bottom"></p><p><br></p>{
	=<p>Elektrisering en verwondingen door hitte, straling of wegspringende delen.</p>
	~<p>Elektrisering en brandwonden.</p>#<p align\="center">&nbsp;<iframe 0\="" height\="360" id\="ytplayer" src\="https\://www.youtube.com/embed/SO6zdetC7N0?autoplay\=0&amp;loop\=1&amp;frameborder\=0&amp;iv_load_policy\=3&amp;modestbranding\=1&amp;showinfo\=0&amp;controls\=1&amp;rel\=0" type\="text/html" width\="640"></iframe></p>
	~<p>Elektrocutie en Elektrisering.</p>#<p align\="center">&nbsp;<iframe 0\="" height\="360" id\="ytplayer" src\="https\://www.youtube.com/embed/SO6zdetC7N0?autoplay\=0&amp;loop\=1&amp;frameborder\=0&amp;iv_load_policy\=3&amp;modestbranding\=1&amp;showinfo\=0&amp;controls\=1&amp;rel\=0" type\="text/html" width\="640"></iframe></p>
	~<p>Elektrisering en verwondingen door straling en bewegende delen.</p>#<p align\="center">&nbsp;<iframe 0\="" height\="360" id\="ytplayer" src\="https\://www.youtube.com/embed/SO6zdetC7N0?autoplay\=0&amp;loop\=1&amp;frameborder\=0&amp;iv_load_policy\=3&amp;modestbranding\=1&amp;showinfo\=0&amp;controls\=1&amp;rel\=0" type\="text/html" width\="640"></iframe></p>
	~<p>Ik weet het niet!</p>#<p align\="center">&nbsp;<iframe 0\="" height\="360" id\="ytplayer" src\="https\://www.youtube.com/embed/SO6zdetC7N0?autoplay\=0&amp;loop\=1&amp;frameborder\=0&amp;iv_load_policy\=3&amp;modestbranding\=1&amp;showinfo\=0&amp;controls\=1&amp;rel\=0" type\="text/html" width\="640"></iframe></p>
}

**Comment by fuhrmanator** [comment]
Hello,

Sorry for such a late reply. I'm not sure your GIFT export is correct (many `=` must be escaped). Are you sure that is how it has been exported from Moodle? Also, I have updated the parser a few times since your report.

Anyway, if you escape the `=` and `:` according to the GIFT standard, it parses well:

```
// question: 3683 name: BV1-P01
::BV1-P01::[html]
Wat zijn de gevaren en risico's bij het werken aan of in de omgeving van elektrische installaties?
<img src\="https\://lh3.googleusercontent.com/3_GX8SlrP7oJAjZAvNUJ9ymtx-O7QFn6gWfWXjkp0txEeH5BL7okuzY2s22YCFZhvVJ6m1P3PQ-gpWkKXkAcfd_wHq8_ozgOKj39VGOMl4slTvkbCHeNdAc13DFcFXfmI2S9Gb5snA\=w2400" alt\="BV1_P1_Elec_Model.jpg" width\="400" height\="300" class\="img-responsive atto_image_button_text-bottom">
{
=
Elektrisering en verwondingen door hitte, straling of wegspringende delen.
~
Elektrisering en brandwonden.
#<p align\="center"> <iframe 0\="" height\="360" id\="ytplayer" src\="https\://www.youtube.com/embed/SO6zdetC7N0?autoplay\=0&loop\=1&frameborder\=0&iv_load_policy\=3&modestbranding\=1&showinfo\=0&controls\=1&rel\=0" type\="text/html" width\="640"></iframe>
~
Elektrocutie en Elektrisering.
#<p align\="center"> <iframe 0\="" height\="360" id\="ytplayer" src\="https\://www.youtube.com/embed/SO6zdetC7N0?autoplay\=0&loop\=1&frameborder\=0&iv_load_policy\=3&modestbranding\=1&showinfo\=0&controls\=1&rel\=0" type\="text/html" width\="640"></iframe>
~
Elektrisering en verwondingen door straling en bewegende delen.
#<p align\="center"> <iframe 0\="" height\="360" id\="ytplayer" src\="https\://www.youtube.com/embed/SO6zdetC7N0?autoplay\=0&loop\=1&frameborder\=0&iv_load_policy\=3&modestbranding\=1&showinfo\=0&controls\=1&rel\=0" type\="text/html" width\="640"></iframe>
~
Ik weet het niet!
#<p align\="center"> <iframe 0\="" height\="360" id\="ytplayer" src\="https\://www.youtube.com/embed/SO6zdetC7N0?autoplay\=0&loop\=1&frameborder\=0&iv_load_policy\=3&modestbranding\=1&showinfo\=0&controls\=1&rel\=0" type\="text/html" width\="640"></iframe>
}
```

It's better to track these bugs in the [main parser repo](https://github.com/fuhrmanator/GIFT-grammar-PEG.js).
