### ISSUE TITLE
Your Add-on completely deleted our form

### ISSUE THREAD

**Issue by drnetter** [Girardvjonathan/GIFT-google-quiz-plugin#17]
We installed your add-on on our already existing form and it completely deleted our questionnaire. This represents a loss of hours of hard work... 

Do you have any solution to retrieve our orginal form?

**Comment by fuhrmanator** [comment]
I'm sorry you lost your work! 

As for a solution, I experimented with the use-case and found that the [Undo](https://support.google.com/docs/answer/2839737?hl=en) feature (under the "More" three-dots menu on the upper right) will get a form back after the add-on has replaced it (you might have to do Undo MANY times). However, I can't guarantee this will work after some time. Again, I feel bad that you lost your form, and hope you can get it back.

Today, I have changed the add-on to make the buttons more clear, and to confirm before removing a form. This should not happen again to anyone.
