### ISSUE TITLE
Pasting properly formatted questions doesn't setup form (Importing questions)

### ISSUE THREAD

**Issue by yositune** [Girardvjonathan/GIFT-google-quiz-plugin#9]
I have a variety of GIFT format questions I've tried pasting into the editing pane to generate form questions.. unsuccessfully.  I will look at the implementation but thought I'd post.  Endgame is to port Moodle question lists into GForms.

**Comment by fuhrmanator** [comment]
Currently, the latest version of the PEG.js grammar isn't in the GIFT add-on. Can you try your questions at https://fuhrmanator.github.io/GIFT-grammar-PEG.js/docs/editor/ and let me know if they parse? 

Meanwhile, I'm going to create an issue here to update the add-on with the latest grammar.

**Comment by fuhrmanator** [comment]
A lot has changed, so I will close this. Can you try again?
